In [1]:
import numpy as np

In [32]:
np.__version__

'1.18.5'

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a.transpose() #转置方法，把行索引和列索引交换位置

array([1, 2, 3, 4])

 ```
 转置方法在numpy中对一维数组无效
 ```

In [5]:
a_t=a[:,np.newaxis] #表示为列向量
a_t

array([[1],
       [2],
       [3],
       [4]])

In [9]:
A = np.array([[1,2,3,4]]) #加一个括号，生成一个1*n的矩阵
A.T

array([[1],
       [2],
       [3],
       [4]])

```
向量的加法
```

In [13]:
u = np.array([[1,2,3]]).T
v = np.array([[5,6,7]]).T
print(u)
print('-'*20)
print(v)
print('-'*20)
print(u+v)

[[1]
 [2]
 [3]]
--------------------
[[5]
 [6]
 [7]]
--------------------
[[ 6]
 [ 8]
 [10]]


```
向量的乘法
1.内积
```

In [14]:
print(3*u)

[[3]
 [6]
 [9]]


In [20]:
print(np.dot(u,v)) #np.dot 传入的参数必须是行向量

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [27]:
u1 = np.array([3,5,2])
v1 = np.array([1,4,7])
print(np.dot(u1,v1))
type(np.dot(u1,v1)) #结果为纯数值

37


numpy.int32

```
向量的本质是矩阵，只不过是行数为1的特殊矩阵，若使用dot，就会按照矩阵的乘法，所以程序报错。
```

In [25]:
u2 = np.array([[3,5,2]])
v2 = np.array([[1,4,7]]).T
print(np.dot(u2,v2)) #正确的使用方法
type(np.dot(u2,v2)) #显示的结果不再是纯数字

[[37]]


numpy.ndarray

```
向量的外积
```

In [29]:
u3 = np.array([3,5])
v3 = np.array([1,4])
print(np.cross(u3,v3))

7


In [30]:
x = np.array([3,3,9])
y = np.array([1,4,12])
print(np.cross(x,y)) #三维的外积计算

[  0 -27   9]


```
向量的线性组合，先数乘后叠加
```

In [31]:
u4 = np.array([[1,2,3]]).T
v4 = np.array([[4,5,6]]).T
w4 = np.array([[7,8,9]]).T
print(3*u4+4*v4+5*w4)


[[54]
 [66]
 [78]]
