In [3]:
import numpy as np
np.__version__

'1.18.5'

In [4]:
A=np.array([[1,2],[3,4],[5,6],[7,8]]) #4行2列的矩阵
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [6]:
A1 = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
print(A1)
print(A1.shape)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
(4, 4)


In [8]:
A2 = A.reshape(2,4)
A2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
A2.T #矩阵转置

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

```
原矩阵和转置后的矩阵相等，则称为对称矩阵
```

In [13]:
S = np.array([[1,2,3,4]
             ,[2,5,6,7]
             ,[3,6,8,9]
             ,[4,7,9,0]])
S.T

array([[1, 2, 3, 4],
       [2, 5, 6, 7],
       [3, 6, 8, 9],
       [4, 7, 9, 0]])

```
零矩阵。所有元素都等于0
```

In [14]:
A3 = np.zeros([5,3])
A3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

```
单位矩阵。对角位置元素为1.
```

In [15]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

```
向量可以被看作一维矩阵。
```

In [16]:
p = np.array([[1,2,3,4]])
print(p)
print(p.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


```
矩阵的加法，必须在两个相等规模的矩阵之间。
```

In [17]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[10,20],[30,40],[50,60]])
print(A+B)

[[11 22]
 [33 44]
 [55 66]]


```
矩阵乘法
```

In [18]:
print(A*B)

[[ 10  40]
 [ 90 160]
 [250 360]]


In [19]:
print(2*A)

[[ 2  4]
 [ 6  8]
 [10 12]]


```
矩阵与矩阵的乘法。
```

In [20]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[2,3,4,5],[6,7,8,9]])
print(np.dot(A,B))

[[ 14  17  20  23]
 [ 30  37  44  51]
 [ 46  57  68  79]
 [ 62  77  92 107]]
